apiVersion: v1
kind: ConfigMap
metadata:
  name: dbt-profiles
data:
  profiles.yml: |
    datapipeline:
      target: dev
      outputs:
        dev:
          type: postgres
          host: "{{ `{{ env_var('DB_HOST') }}` }}"
          user: "{{ `{{ env_var('DB_USER') }}` }}"
          password: "{{ `{{ env_var('DB_PASSWORD') }}` }}"
          port: 5432
          dbname: "{{ `{{ env_var('DB_NAME') }}` }}"
          schema: "analytics"
