apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: inventory-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: k8s-store-local
    kind: SecretStore
  target:
    name: inventory-secret
    template:
      engineVersion: v2
      data: 
        inventory.properties: |
          dbname={{ `{{ .dbname }}` }}
          hostname={{ `{{ .hostname }}` }}
          password={{ `{{ .password }}` }}
          user={{ `{{ .user }}` }}
  data:  
  - secretKey: dbname
    remoteRef:
      key: inventoryservice-pguser-inventoryservice
      property: dbname  
  - secretKey: hostname
    remoteRef:
      key: inventoryservice-pguser-inventoryservice
      property: host	
  - secretKey: user
    remoteRef:
      key: inventoryservice-pguser-inventoryservice
      property: user	
  - secretKey: password
    remoteRef:
      key: inventoryservice-pguser-inventoryservice
      property: password