apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: keycloak-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: k8s-store-infrastructure
    kind: SecretStore
  target:
    name: keycloak-secret
    template:
      engineVersion: v2
      data: 
        keycloak.properties: |
          dbname={{ `{{ .dbname }}` }}
          hostname={{ `{{ .hostname }}` }}
          password={{ `{{ .password }}` }}
          user={{ `{{ .user }}` }}
  data:  
  - secretKey: dbname
    remoteRef:
      key: keycloak-pguser-keycloak
      property: dbname  
  - secretKey: hostname
    remoteRef:
      key: keycloak-pguser-keycloak
      property: host	
  - secretKey: user
    remoteRef:
      key: keycloak-pguser-keycloak
      property: user	
  - secretKey: password
    remoteRef:
      key: keycloak-pguser-keycloak
      property: password