apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: reservation-connector-sink
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  configs:
    connection.url: "${file:/mnt/secrets/data-secret/data.properties:url}&currentSchema=reservationservice"
    connection.password: "${file:/mnt/secrets/data-secret/data.properties:password}"
    connection.user: "${file:/mnt/secrets/data-secret/data.properties:user}"
    topics.regex: "^(?!.*\\.shedlock$)(?!.*\\.revinfo$)reservation{{ .Values.appSuffix }}\\..*\\..*"
    auto.create: "true"
    auto.evolve: "true"
    insert.mode: "upsert"
    pk.mode: "record_key"
    pk.fields: "id"
    delete.enabled: "false"
    table.name.format: "reservationservice.${topic}"
    transforms: "extractTableName"
    transforms.extractTableName.type: "org.apache.kafka.connect.transforms.RegexRouter"
    transforms.extractTableName.regex: "^[^.]+\\.[^.]+\\.(.*)"
    transforms.extractTableName.replacement: "$1" 
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "true"  
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
  connectClusterRef:
    name: connect
  taskMax: 1
