apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-store-infrastructure
spec:
  provider:
    kubernetes:
      remoteNamespace: infrastructure
      auth:
        serviceAccount: 
          name: "eso-store"
      server:
        caProvider: # we are connecting to our own cluster.
          namespace: "default"
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt    	  
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-store-local
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.namespace }}
      auth:
        serviceAccount: 
          name: "eso-store"
      server:
        caProvider: # we are connecting to our own cluster.
          namespace: "default"
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt 
---